// Deep-enrichment overrides: richer versions of read topics, with the by-hand
// methods that show up as exam questions written as original notes (never the
// literal question). Spread LAST in content.js so these win over the base entry.
export const deepContent = {
  'hash-table': {
    tldr: { en: 'Stores key-value pairs by running the key through a <strong>hash function</strong> to pick a bucket. <strong>O(1) average</strong> for insert/lookup/delete, <strong>O(n) worst case</strong> when everything collides. The average is why hash tables are everywhere.', de: 'Speichert Schlüssel-Wert-Paare, indem der Schlüssel über eine <strong>Hashfunktion</strong> einen Behälter wählt. <strong>O(1) im Schnitt</strong>, <strong>O(n) im schlechtesten Fall</strong>, wenn alles kollidiert.', sl: 'Shrani pare ključ-vrednost tako, da ključ požene skozi <strong>zgoščevalno funkcijo</strong>, ki izbere predalček. <strong>O(1) povprečno</strong> za vstavljanje/iskanje/brisanje, <strong>O(n) v najslabšem primeru</strong>, ko vse trči. Povprečje je razlog, da so razpršene tabele povsod.' },
    defs: [
      { name: { en: 'Division method', de: 'Divisionsmethode', sl: 'Metoda deljenja' }, body: { en: 'The simplest hash: the key modulo the table size. Fast, but pick $m$ well (a prime far from a power of two) so every bit of the key influences the bucket.', de: 'Der einfachste Hash: Schlüssel modulo Tabellengrösse. Schnell, aber $m$ gut wählen (eine Primzahl fern einer Zweierpotenz), damit jedes Bit des Schlüssels den Behälter beeinflusst.', sl: 'Najpreprostejše zgoščevanje: ključ po modulu velikosti tabele. Hitro, a $m$ izberi dobro (praštevilo daleč od potence dvojke), da vsak bit ključa vpliva na predalček.' }, formal: { tex: 'h(k) = k \\bmod m' } },
      { name: { en: 'Multiplication method', de: 'Multiplikationsmethode', sl: 'Metoda množenja' }, body: { en: 'Multiply the key by a constant $A \\in (0,1)$, keep the fractional part, then scale to the table. Works for any $m$, even a power of two.', de: 'Multipliziere den Schlüssel mit einer Konstante $A \\in (0,1)$, nimm den Nachkommateil, skaliere auf die Tabelle. Funktioniert für jedes $m$, auch Zweierpotenzen.', sl: 'Ključ pomnoži s konstanto $A \\in (0,1)$, obdrži ulomljeni del, nato preslikaj na tabelo. Deluje za poljuben $m$, tudi za potenco dvojke.' }, formal: { tex: 'h(k) = \\lfloor m\\,(kA - \\lfloor kA \\rfloor) \\rfloor' } },
      { name: { en: 'Quadratic probing', de: 'Quadratisches Sondieren', sl: 'Kvadratično sondiranje' }, body: { en: 'Open addressing where the $i$-th probe steps a quadratic distance from the base slot, breaking up the long runs that linear probing creates.', de: 'Offene Adressierung, bei der die $i$-te Sondierung quadratisch vom Basisplatz abweicht und die langen Ketten des linearen Sondierens aufbricht.', sl: 'Odprto naslavljanje, kjer $i$-ta sonda naredi kvadratično velik korak od osnovnega mesta in razbije dolge nize, ki jih ustvari linearno sondiranje.' }, formal: { tex: "h(k,i) = (h'(k) + c_1 i + c_2 i^2) \\bmod m" } },
      { name: { en: 'Double hashing', de: 'Doppeltes Hashen', sl: 'Dvojno zgoščevanje' }, body: { en: 'Open addressing where a second hash sets the step size, so different keys walk the table in different patterns and clustering almost disappears.', de: 'Offene Adressierung, bei der ein zweiter Hash die Schrittweite setzt, sodass verschiedene Schlüssel die Tabelle unterschiedlich durchlaufen und Cluster fast verschwinden.', sl: 'Odprto naslavljanje, kjer drugo zgoščevanje določi velikost koraka, tako da različni ključi hodijo po tabeli v različnih vzorcih in gručenje skoraj izgine.' }, formal: { tex: 'h(k,i) = (h_1(k) + i\\,h_2(k)) \\bmod m' } },
    ],
    intro: [
      { en: 'A <strong>hash function</strong> turns a key into a bucket index. Two keys landing in the same bucket is a <strong>collision</strong>, resolved either by <strong>chaining</strong> (each bucket holds a list) or <strong>open addressing</strong> (probe on to another slot in the same array).', de: 'Eine <strong>Hashfunktion</strong> macht aus einem Schlüssel einen Behälterindex. Landen zwei Schlüssel im selben Behälter, ist das eine <strong>Kollision</strong>, gelöst durch <strong>Verkettung</strong> (Liste pro Behälter) oder <strong>offene Adressierung</strong> (weiter zu einem anderen Platz im selben Feld sondieren).', sl: '<strong>Zgoščevalna funkcija</strong> spremeni ključ v indeks predalčka. Dva ključa, ki pristaneta v istem predalčku, sta <strong>trk</strong>, razrešen bodisi z <strong>veriženjem</strong> (vsak predalček hrani seznam) bodisi z <strong>odprtim naslavljanjem</strong> (sondiranje na drugo mesto v istem polju).' },
      { en: 'The <strong>load factor</strong> $\\alpha = \\tfrac{n}{m}$ (items over buckets) governs speed. Keep it well below 1 for open addressing; when it grows, allocate a bigger table and <strong>rehash</strong> every key.', de: 'Der <strong>Füllgrad</strong> $\\alpha = \\tfrac{n}{m}$ (Elemente durch Behälter) bestimmt das Tempo. Halte ihn bei offener Adressierung deutlich unter 1; wächst er, ein grösseres Feld anlegen und jeden Schlüssel <strong>neu hashen</strong>.', sl: '<strong>Faktor zasedenosti</strong> $\\alpha = \\tfrac{n}{m}$ (elementi na predalčke) določa hitrost. Pri odprtem naslavljanju ga ohranjaj precej pod 1; ko naraste, dodeli večjo tabelo in vsak ključ <strong>ponovno zgosti</strong>.' },
    ],
    how: [
      { en: 'To build a probe sequence by hand: compute the base slot with the auxiliary hash $h&#39;(k)$, then apply the probing formula for $i = 0, 1, 2, \\dots$ until a free slot appears, taking every result $\\bmod\\ m$.', de: 'Eine Sondierungsfolge von Hand: berechne den Basisplatz mit dem Hilfshash $h&#39;(k)$, wende dann die Sondierungsformel für $i = 0, 1, 2, \\dots$ an, bis ein freier Platz auftaucht, jedes Ergebnis $\\bmod\\ m$.', sl: 'Za ročno gradnjo zaporedja sond: izračunaj osnovno mesto s pomožnim zgoščevanjem $h&#39;(k)$, nato uporabi sondirno formulo za $i = 0, 1, 2, \\dots$, dokler se ne pojavi prosto mesto, vsak rezultat vzemi $\\bmod\\ m$.' },
      { en: 'For <strong>double hashing</strong>, first compute both auxiliary hashes ($h_1$ by division, $h_2$ often by the multiplication method), then step by $h_2$ each probe.', de: 'Beim <strong>doppelten Hashen</strong> zürst beide Hilfshashes berechnen ($h_1$ per Division, $h_2$ oft per Multiplikationsmethode), dann pro Sondierung um $h_2$ weitergehen.', sl: 'Za <strong>dvojno zgoščevanje</strong> najprej izračunaj obe pomožni zgoščevanji ($h_1$ z deljenjem, $h_2$ pogosto z metodo množenja), nato pri vsaki sondi naredi korak $h_2$.' },
    ],
    complexity: [
      { case: { en: 'Insert / Search / Delete - average', de: 'Einf./Suchen/Löschen - Durchschnitt', sl: 'Vstavljanje / iskanje / brisanje, povprečno' }, time: 'O(1)', space: 'O(n)', cls: 'best' },
      { case: { en: 'Insert / Search / Delete - worst', de: 'Einf./Suchen/Löschen - schlecht.', sl: 'Vstavljanje / iskanje / brisanje, najslabše' }, time: 'O(n)', space: 'O(n)', cls: 'worst', note: { en: 'All keys collide into one bucket (bad hash). A good hash plus a low load factor keeps it O(1) amortised.', de: 'Alle Schlüssel kollidieren in einem Behälter (schlechter Hash). Guter Hash plus niedriger Füllgrad hält es bei O(1) amortisiert.', sl: 'Vsi ključi trčijo v en predalček (slabo zgoščevanje). Dobro zgoščevanje in nizek faktor zasedenosti ga ohranjata pri amortizirano O(1).' } },
    ],
    pitfalls: [
      { en: '<strong>Quadratic probing</strong> may not reach every slot: with a bad $m$ it cycles through a fraction of the table and can fail to insert even when space remains.', de: '<strong>Quadratisches Sondieren</strong> erreicht evtl. nicht jeden Platz: bei schlechtem $m$ durchläuft es nur einen Teil der Tabelle und kann trotz freien Platzes scheitern.', sl: '<strong>Kvadratično sondiranje</strong> morda ne doseže vsakega mesta: pri slabem $m$ kroži po delu tabele in lahko ne vstavi, tudi ko prostor ostaja.' },
      { en: '<strong>Double hashing</strong> needs $h_2(k)$ never zero and coprime with $m$, otherwise the step size cannot cover the whole table.', de: '<strong>Doppeltes Hashen</strong> braucht $h_2(k)$ nie null und teilerfremd zu $m$, sonst deckt die Schrittweite nicht die ganze Tabelle ab.', sl: '<strong>Dvojno zgoščevanje</strong> potrebuje, da $h_2(k)$ ni nikoli nič in je tuje z $m$, sicer velikost koraka ne more pokriti cele tabele.' },
      { en: 'The division method with $m$ a power of two only looks at the low bits of the key, throwing away the rest. Prefer a prime.', de: 'Die Divisionsmethode mit $m$ als Zweierpotenz betrachtet nur die niederen Bits des Schlüssels und verwirft den Rest. Bevorzuge eine Primzahl.', sl: 'Metoda deljenja z $m$ kot potenco dvojke gleda le spodnje bite ključa in zavrže preostanek. Raje izberi praštevilo.' },
    ],
  },

  'big-o': {
    tldr: { en: '<strong>Big-O</strong> describes how a runtime or memory grows with the input size $n$, keeping only the dominant term and dropping constants. It is the language for comparing algorithms independent of the machine.', de: '<strong>Big-O</strong> beschreibt, wie Laufzeit oder Speicher mit der Eingabegrösse $n$ wächst, behält nur den dominanten Term und lässt Konstanten weg. Die Sprache zum maschinenunabhängigen Vergleich von Algorithmen.', sl: '<strong>Big-O</strong> opisuje, kako čas izvajanja ali pomnilnik rasteta z velikostjo vhoda $n$, pri čemer obdrži le prevladujoči člen in izpusti konstante. Je jezik za primerjavo algoritmov neodvisno od stroja.' },
    defs: [
      { name: { en: 'Big-O (upper bound)', de: 'Big-O (obere Schranke)', sl: 'Big-O (zgornja meja)' }, body: { en: '$f(n) = O(g(n))$ means $f$ grows no faster than $g$, up to a constant, for large $n$. The everyday worst-case bound.', de: '$f(n) = O(g(n))$ heisst, $f$ wächst höchstens so schnell wie $g$, bis auf eine Konstante, für grosse $n$. Die übliche Worst-Case-Schranke.', sl: '$f(n) = O(g(n))$ pomeni, da $f$ ne raste hitreje kot $g$, do konstante, za velike $n$. Vsakdanja meja najslabšega primera.' }, formal: { tex: 'f(n) \\le c\\,g(n) \\ \\text{ for } n \\ge n_0' } },
      { name: { en: 'Big-Omega (lower bound)', de: 'Big-Omega (untere Schranke)', sl: 'Big-Omega (spodnja meja)' }, body: { en: '$\\Omega(g)$ is a lower bound: $f$ grows at least as fast as $g$.', de: '$\\Omega(g)$ ist eine untere Schranke: $f$ wächst mindestens so schnell wie $g$.', sl: '$\\Omega(g)$ je spodnja meja: $f$ raste vsaj tako hitro kot $g$.' }, formal: { tex: 'f(n) \\ge c\\,g(n) \\ \\text{ for } n \\ge n_0' } },
      { name: { en: 'Big-Theta (tight)', de: 'Big-Theta (scharf)', sl: 'Big-Theta (tesna)' }, body: { en: '$\\Theta(g)$ means both bounds hold: $f$ grows exactly like $g$.', de: '$\\Theta(g)$ heisst, beide Schranken gelten: $f$ wächst genau wie $g$.', sl: '$\\Theta(g)$ pomeni, da veljata obe meji: $f$ raste natanko kot $g$.' }, formal: { tex: 'c_1 g(n) \\le f(n) \\le c_2 g(n)' } },
    ],
    intro: [
      { en: 'The common growth classes, slowest-growing first: constant $O(1)$, logarithmic $O(\\log n)$, linear $O(n)$, linearithmic $O(n \\log n)$, quadratic $O(n^2)$, and exponential $O(2^n)$. The gap between them dwarfs any constant factor once $n$ is large.', de: 'Die gängigen Wachstumsklassen, langsamste zürst: konstant $O(1)$, logarithmisch $O(\\log n)$, linear $O(n)$, linearithmisch $O(n \\log n)$, quadratisch $O(n^2)$, exponentiell $O(2^n)$. Der Abstand zwischen ihnen überwiegt jeden konstanten Faktor, sobald $n$ gross ist.', sl: 'Pogosti razredi rasti, od najpočasnejšega: konstantni $O(1)$, logaritemski $O(\\log n)$, linearni $O(n)$, linearitmični $O(n \\log n)$, kvadratni $O(n^2)$ in eksponentni $O(2^n)$. Vrzel med njimi prekaša vsak konstantni faktor, ko je $n$ velik.' },
    ],
    how: [
      { en: '<strong>Scaling with a faster machine:</strong> if a run takes time proportional to $T(n)$ and the machine speeds up by a factor $s$, the largest solvable size grows by solving $T(n_2) = s\\,T(n_1)$. For $T(n) = n^k$ this means $n_2 = \\sqrt[k]{s}\\;n_1$, so faster hardware buys only a $k$-th root of the size for polynomial costs, and almost nothing for exponential ones.', de: '<strong>Skalierung mit schnellerer Maschine:</strong> braucht ein Lauf Zeit proportional zu $T(n)$ und die Maschine wird um Faktor $s$ schneller, folgt die grösste lösbare Grösse aus $T(n_2) = s\\,T(n_1)$. Für $T(n) = n^k$ heisst das $n_2 = \\sqrt[k]{s}\\;n_1$, schnellere Hardware bringt also nur eine $k$-te Wurzel der Grösse bei Polynomen und fast nichts bei Exponentiellem.', sl: '<strong>Skaliranje s hitrejšim strojem:</strong> če tek traja sorazmerno s $T(n)$ in stroj pohitri za faktor $s$, se največja rešljiva velikost poveča z reševanjem $T(n_2) = s\\,T(n_1)$. Za $T(n) = n^k$ to pomeni $n_2 = \\sqrt[k]{s}\\;n_1$, tako da hitrejša strojna oprema pri polinomskih stroških kupi le $k$-ti koren velikosti, pri eksponentnih pa skoraj nič.' },
      { en: '<strong>Fitting a cost from two measurements:</strong> if you assume a form like $T(n) = a\\,2^{k n}$ and measure two times, divide the two equations to cancel $a$, take a logarithm to solve for $k$, then back-substitute for $a$. This turns two data points into a predictive formula.', de: '<strong>Kosten aus zwei Messungen bestimmen:</strong> nimmst du eine Form wie $T(n) = a\\,2^{k n}$ an und misst zweimal, teile die Gleichungen, um $a$ zu kürzen, logarithmiere für $k$ und setze zurück für $a$. So werden zwei Messpunkte zu einer Vorhersageformel.', sl: '<strong>Prileganje stroška iz dveh meritev:</strong> če predpostaviš obliko, kot je $T(n) = a\\,2^{k n}$, in izmeriš dvakrat, deli enačbi, da pokrajšaš $a$, logaritmiraj za $k$ in vstavi nazaj za $a$. Tako dve merilni točki postaneta napovedna formula.' },
    ],
    pitfalls: [
      { en: 'Big-O hides constants and lower-order terms, so a "slower" class can win for small $n$. It describes <strong>asymptotic</strong> behaviour, not a stopwatch.', de: 'Big-O verbirgt Konstanten und Terme niedriger Ordnung, eine "langsamere" Klasse kann für kleine $n$ gewinnen. Es beschreibt <strong>asymptotisches</strong> Verhalten, keine Stoppuhr.', sl: 'Big-O skriva konstante in člene nižjega reda, zato lahko "počasnejši" razred zmaga za majhne $n$. Opisuje <strong>asimptotično</strong> vedenje, ne štoparice.' },
      { en: 'Best, average and worst case can differ (quicksort is $O(n \\log n)$ average but $O(n^2)$ worst). State which one you mean.', de: 'Bester, mittlerer und schlechtester Fall können sich unterscheiden (Quicksort ist $O(n \\log n)$ im Schnitt, aber $O(n^2)$ schlecht). Sag, welchen du meinst.', sl: 'Najboljši, povprečni in najslabši primer se lahko razlikujejo (hitro urejanje je $O(n \\log n)$ povprečno, a $O(n^2)$ najslabše). Povej, katerega misliš.' },
    ],
  },

  'linked-list': {
    tldr: { en: 'A chain of <strong>nodes</strong>, each holding a value and a pointer to the next. Insert and delete at a known position are <strong>O(1)</strong>, but there is <strong>no random access</strong>: reaching the $k$-th element costs $O(k)$.', de: 'Eine Kette von <strong>Knoten</strong>, jeder mit einem Wert und einem Zeiger auf den nächsten. Einfügen und Löschen an bekannter Stelle ist <strong>O(1)</strong>, aber es gibt <strong>keinen wahlfreien Zugriff</strong>: das $k$-te Element kostet $O(k)$.', sl: 'Veriga <strong>vozlišč</strong>, vsako hrani vrednost in kazalec na naslednje. Vstavljanje in brisanje na znanem mestu sta <strong>O(1)</strong>, a <strong>naključnega dostopa ni</strong>: doseg $k$-tega elementa stane $O(k)$.' },
    defs: [
      { name: { en: 'Singly linked', de: 'Einfach verkettet', sl: 'Enojno povezan' }, body: { en: 'Each node points only forward. Traversal is one-way; you keep a head pointer to the first node.', de: 'Jeder Knoten zeigt nur vorwärts. Durchlauf ist einseitig; ein Kopfzeiger hält den ersten Knoten.', sl: 'Vsako vozlišče kaže le naprej. Prehod je enosmeren; obdržiš kazalec na glavo, tj. prvo vozlišče.' } },
      { name: { en: 'Doubly linked', de: 'Doppelt verkettet', sl: 'Dvojno povezan' }, body: { en: 'Each node points both forward and back, so you can delete a node in $O(1)$ given only that node, and walk in either direction.', de: 'Jeder Knoten zeigt vor und zurück, sodass man einen Knoten in $O(1)$ nur mit diesem Knoten löschen und in beide Richtungen laufen kann.', sl: 'Vsako vozlišče kaže naprej in nazaj, tako da lahko vozlišče izbrišeš v $O(1)$, če imaš le to vozlišče, in hodiš v obe smeri.' } },
      { name: { en: 'Circular', de: 'Zirkulär', sl: 'Krožni' }, body: { en: 'The last node points back to the first, handy for round-robin scheduling and ring buffers.', de: 'Der letzte Knoten zeigt zurück auf den ersten, praktisch für Round-Robin und Ringpuffer.', sl: 'Zadnje vozlišče kaže nazaj na prvo, priročno za krožno razvrščanje in obročne medpomnilnike.' } },
    ],
    intro: [
      { en: 'Unlike an array, a linked list is not one contiguous block; each node is allocated separately and found only through the pointer from its predecessor. That is what makes insertion cheap (relink two pointers) and indexing expensive (walk from the head).', de: 'Anders als ein Feld ist eine verkettete Liste kein zusammenhängender Block; jeder Knoten wird einzeln angelegt und nur über den Zeiger seines Vorgängers gefunden. Das macht Einfügen billig (zwei Zeiger umhängen) und Indizieren teuer (vom Kopf laufen).', sl: 'Za razliko od polja povezan seznam ni en zvezni blok; vsako vozlišče je dodeljeno posebej in ga najdeš le prek kazalca od njegovega predhodnika. Prav to naredi vstavljanje poceni (prevežeš dva kazalca) in indeksiranje drago (hoja od glave).' },
    ],
    how: [
      { en: '<strong>Insert at head:</strong> point the new node at the old head, then move the head pointer. $O(1)$.', de: '<strong>Am Kopf einfügen:</strong> neuen Knoten auf den alten Kopf zeigen lassen, dann Kopfzeiger versetzen. $O(1)$.', sl: '<strong>Vstavi na glavo:</strong> novo vozlišče usmeri na staro glavo, nato premakni kazalec glave. $O(1)$.' },
      { en: '<strong>Delete a node:</strong> relink its predecessor to its successor. $O(1)$ once you hold the node (doubly linked) or its predecessor (singly linked).', de: '<strong>Knoten löschen:</strong> Vorgänger auf Nachfolger umhängen. $O(1)$, sobald man den Knoten hält (doppelt) oder seinen Vorgänger (einfach).', sl: '<strong>Izbriši vozlišče:</strong> prevežej njegovega predhodnika na naslednika. $O(1)$, ko držiš vozlišče (dvojno povezan) ali njegovega predhodnika (enojno povezan).' },
    ],
    complexity: [
      { case: { en: 'Insert / delete at position', de: 'Einf./Löschen an Position', sl: 'Vstavljanje / brisanje na mestu' }, time: 'O(1)', space: 'O(n)', cls: 'best' },
      { case: { en: 'Access / search k-th', de: 'Zugriff / Suche k-tes', sl: 'Dostop / iskanje k-tega' }, time: 'O(n)', space: 'O(n)', cls: 'worst' },
    ],
    pitfalls: [
      { en: 'Losing the pointer to the rest of the list mid-operation leaks or drops nodes. Reassign pointers in the right order, and guard the empty and single-node cases.', de: 'Den Zeiger auf den Rest der Liste mitten in der Operation zu verlieren, verliert Knoten. Zeiger in der richtigen Reihenfolge setzen und die Fälle leere Liste und ein Knoten absichern.', sl: 'Izguba kazalca na preostanek seznama sredi operacije pušča ali izpušča vozlišča. Kazalce priredi v pravem vrstnem redu ter varuj primera praznega in enega vozlišča.' },
    ],
  },

  'stack-queue': {
    tldr: { en: 'Two restricted lists. A <strong>stack</strong> is <strong>LIFO</strong> (last in, first out); a <strong>queue</strong> is <strong>FIFO</strong> (first in, first out). Both do their core operations in <strong>O(1)</strong>.', de: 'Zwei eingeschränkte Listen. Ein <strong>Stapel</strong> ist <strong>LIFO</strong> (zuletzt rein, zürst raus); eine <strong>Warteschlange</strong> ist <strong>FIFO</strong> (zürst rein, zürst raus). Beide Kernoperationen in <strong>O(1)</strong>.', sl: 'Dva omejena seznama. <strong>Sklad</strong> je <strong>LIFO</strong> (zadnji noter, prvi ven); <strong>vrsta</strong> je <strong>FIFO</strong> (prvi noter, prvi ven). Oba svoje temeljne operacije izvedeta v <strong>O(1)</strong>.' },
    defs: [
      { name: { en: 'Stack (LIFO)', de: 'Stapel (LIFO)', sl: 'Sklad (LIFO)' }, body: { en: 'Push adds to the top, pop removes from the top. Models call stacks, undo, and expression evaluation.', de: 'Push legt oben ab, Pop nimmt oben weg. Modelliert Aufrufstapel, Rückgängig und Ausdrucksauswertung.', sl: 'Push doda na vrh, pop odstrani z vrha. Modelira klicne sklade, razveljavitev in vrednotenje izrazov.' } },
      { name: { en: 'Queue (FIFO)', de: 'Warteschlange (FIFO)', sl: 'Vrsta (FIFO)' }, body: { en: 'Enqueue adds at the back, dequeue removes from the front. Models buffers, scheduling, and BFS.', de: 'Enqueue hängt hinten an, Dequeue nimmt vorne weg. Modelliert Puffer, Scheduling und BFS.', sl: 'Enqueue doda na zadnji del, dequeue odstrani s sprednjega. Modelira medpomnilnike, razvrščanje in BFS.' } },
      { name: { en: 'Circular queue', de: 'Ringpuffer', sl: 'Krožna vrsta' }, body: { en: 'A fixed array whose front and back indices wrap around modulo the capacity, reusing freed slots without shifting.', de: 'Ein festes Feld, dessen Vorder- und Hinterindex modulo der Kapazität umlaufen und freie Plätze ohne Verschieben wiederverwenden.', sl: 'Polje fiksne velikosti, katerega sprednji in zadnji indeks se ovijeta po modulu kapacitete in znova uporabita sproščena mesta brez premikanja.' }, formal: { tex: 'i_{next} = (i + 1) \\bmod \\text{capacity}' } },
    ],
    how: [
      { en: '<strong>Stack:</strong> keep a top index; push writes then increments, pop decrements then reads.', de: '<strong>Stapel:</strong> einen Top-Index halten; Push schreibt und erhöht, Pop verringert und liest.', sl: '<strong>Sklad:</strong> ohranjaj vrhnji indeks; push zapiše, nato poveča, pop zmanjša, nato prebere.' },
      { en: '<strong>Circular queue:</strong> advance front and back with $\\bmod$ capacity; track a count (or leave one slot empty) to tell a full queue from an empty one.', de: '<strong>Ringpuffer:</strong> Front und Back mit $\\bmod$ Kapazität weiterschalten; einen Zähler führen (oder einen Platz frei lassen), um voll von leer zu unterscheiden.', sl: '<strong>Krožna vrsta:</strong> sprednji in zadnji premikaj z $\\bmod$ kapaciteto; sledi števcu (ali pusti eno mesto prazno), da ločiš polno vrsto od prazne.' },
    ],
    pitfalls: [
      { en: 'In a circular queue, front and back are equal both when it is <strong>empty and full</strong>. Resolve it with an explicit size counter or by keeping one slot always empty.', de: 'Im Ringpuffer sind Front und Back sowohl bei <strong>leer als auch voll</strong> gleich. Löse es mit einem Grössenzähler oder indem ein Platz stets frei bleibt.', sl: 'V krožni vrsti sta sprednji in zadnji enaka, ko je <strong>prazna in polna</strong>. Razreši z izrecnim števcem velikosti ali tako, da eno mesto vedno ostane prazno.' },
      { en: 'Popping an empty stack (underflow) or pushing a full fixed stack (overflow) must be checked, not assumed away.', de: 'Pop auf leerem Stapel (Unterlauf) oder Push auf vollem festen Stapel (Überlauf) muss geprüft, nicht angenommen werden.', sl: 'Pop praznega sklada (podkoračitev) ali push polnega fiksnega sklada (prekoračitev) je treba preveriti, ne predpostaviti stran.' },
    ],
  },
}
