// Web Foundations: CSS, JavaScript, async, security, frameworks.
// Original explanations matched to the curriculum topics, not copied from any slides.
export const webContent = {
  'css': {
    tldr: {
      en: '<strong>CSS</strong> controls how HTML looks. Its core ideas are the <strong>cascade</strong> (which rule wins), the <strong>box model</strong> (every element is a box of content, padding, border and margin), and modern layout with <strong>Flexbox</strong> and <strong>Grid</strong>. It keeps presentation separate from structure.', de: '<strong>CSS</strong> steuert das Aussehen von HTML. Kernideen sind die <strong>Kaskade</strong> (welche Regel gewinnt), das <strong>Boxmodell</strong> (jedes Element ist eine Box aus Inhalt, Innenabstand, Rahmen und Aussenabstand) und modernes Layout mit <strong>Flexbox</strong> und <strong>Grid</strong>. Darstellung bleibt von Struktur getrennt.', sl: '<strong>CSS</strong> določa videz HTML. Njegove temeljne ideje so <strong>kaskada</strong> (katero pravilo prevlada), <strong>škatlični model</strong> (vsak element je škatla iz vsebine, notranjega odmika, obrobe in zunanjega odmika) ter sodobna postavitev s <strong>Flexbox</strong> in <strong>Grid</strong>. Predstavitev ohranja ločeno od strukture.',
    },
    intro: [
      { en: 'When two rules target the same element, the <strong>cascade</strong> decides the winner by <strong>specificity</strong> (an id beats a class beats an element), then by source order. Some properties (like <code>color</code> and <code>font</code>) also <strong>inherit</strong> from parent to child.', de: 'Zielen zwei Regeln auf dasselbe Element, entscheidet die <strong>Kaskade</strong> nach <strong>Spezifität</strong> (id schlägt Klasse schlägt Element), dann nach Reihenfolge. Manche Eigenschaften (wie <code>color</code>, <code>font</code>) <strong>vererben</strong> sich zudem vom Eltern- zum Kindelement.', sl: 'Kadar dve pravili ciljata isti element, <strong>kaskada</strong> določi zmagovalca po <strong>specifičnosti</strong> (id premaga razred, razred premaga element), nato po vrstnem redu v viru. Nekatere lastnosti (kot <code>color</code> in <code>font</code>) se tudi <strong>dedujejo</strong> s starša na otroka.' },
      { en: 'Every element is a rectangular box: <strong>content</strong> at the centre, then <strong>padding</strong>, then a <strong>border</strong>, then <strong>margin</strong> outside. <code>box-sizing: border-box</code> makes width include padding and border, which is far easier to reason about.', de: 'Jedes Element ist ein Rechteck: <strong>Inhalt</strong> in der Mitte, dann <strong>Innenabstand</strong>, dann <strong>Rahmen</strong>, dann <strong>Aussenabstand</strong>. <code>box-sizing: border-box</code> lässt die Breite Innenabstand und Rahmen einschliessen, was das Rechnen stark vereinfacht.', sl: 'Vsak element je pravokotna škatla: <strong>vsebina</strong> v sredini, nato <strong>notranji odmik</strong>, nato <strong>obroba</strong>, nato <strong>zunanji odmik</strong>. <code>box-sizing: border-box</code> doseže, da širina vključuje notranji odmik in obrobo, kar je veliko lažje razumeti.' },
    ],
    how: [
      { en: '<strong>Selectors:</strong> target by element (<code>p</code>), class (<code>.card</code>), id (<code>#nav</code>), or combinators (<code>.card &gt; h2</code>).', de: '<strong>Selektoren:</strong> nach Element (<code>p</code>), Klasse (<code>.card</code>), id (<code>#nav</code>) oder Kombinatoren (<code>.card &gt; h2</code>).', sl: '<strong>Selektorji:</strong> ciljaj po elementu (<code>p</code>), razredu (<code>.card</code>), id-ju (<code>#nav</code>) ali kombinatorjih (<code>.card &gt; h2</code>).' },
      { en: '<strong>Flexbox</strong> lays out items in one dimension (a row or a column) and is ideal for toolbars and centring.', de: '<strong>Flexbox</strong> ordnet Elemente in einer Dimension (Zeile oder Spalte) an, ideal für Leisten und Zentrieren.', sl: '<strong>Flexbox</strong> razporeja elemente v eni dimenziji (vrstica ali stolpec) in je idealen za orodne vrstice in centriranje.' },
      { en: '<strong>Grid</strong> lays out in two dimensions (rows and columns at once), ideal for page and card layouts. <strong>Media queries</strong> adapt the design to screen width.', de: '<strong>Grid</strong> ordnet in zwei Dimensionen an (Zeilen und Spalten zugleich), ideal für Seiten- und Kartenlayouts. <strong>Media Queries</strong> passen das Design an die Bildschirmbreite an.', sl: '<strong>Grid</strong> razporeja v dveh dimenzijah (vrstice in stolpci hkrati), idealen za postavitve strani in kartic. <strong>Medijske poizvedbe</strong> prilagodijo videz širini zaslona.' },
    ],
    pitfalls: [
      { en: 'Fighting specificity with ever-more-specific selectors (or <code>!important</code>) makes stylesheets unmaintainable. Keep selectors flat and lean on classes.', de: 'Spezifität mit immer spezifischeren Selektoren (oder <code>!important</code>) zu bekämpfen macht Stylesheets unwartbar. Halte Selektoren flach und setze auf Klassen.', sl: 'Boj s specifičnostjo z vse bolj specifičnimi selektorji (ali <code>!important</code>) naredi sloge nevzdržne. Ohranjaj selektorje plitve in se opiraj na razrede.' },
    ],
  },

  'javascript': {
    tldr: {
      en: '<strong>JavaScript</strong> is the language that runs in the browser. It is dynamically typed. <strong>Objects</strong> group data and behaviour as key-value pairs; <strong>prototypes</strong> power inheritance; and ES6 <strong>classes</strong> are syntactic sugar over those prototypes.', de: '<strong>JavaScript</strong> ist die Sprache im Browser. Sie ist dynamisch typisiert. <strong>Objekte</strong> gruppieren Daten und Verhalten als Schlüssel-Wert-Paare; <strong>Prototypen</strong> ermöglichen Vererbung; und ES6-<strong>Klassen</strong> sind syntaktischer Zucker über diesen Prototypen.', sl: '<strong>JavaScript</strong> je jezik, ki teče v brskalniku. Je dinamično tipiziran. <strong>Objekti</strong> združujejo podatke in vedenje kot pare ključ-vrednost; <strong>prototipi</strong> poganjajo dedovanje; <strong>razredi</strong> ES6 pa so sintaktični sladkor nad temi prototipi.',
    },
    intro: [
      { en: 'An object is a bag of properties: <code>{ name: "Ann", greet() { ... } }</code>. Every object links to a <strong>prototype</strong>, and when a property is missing JavaScript walks up that prototype chain to find it. This is how shared methods are stored once and reused by many objects.', de: 'Ein Objekt ist eine Sammlung von Eigenschaften: <code>{ name: "Ann", greet() { ... } }</code>. Jedes Objekt verweist auf einen <strong>Prototyp</strong>, und fehlt eine Eigenschaft, geht JavaScript die Prototypkette hinauf, um sie zu finden. So werden geteilte Methoden einmal gespeichert und von vielen Objekten genutzt.', sl: 'Objekt je vreča lastnosti: <code>{ name: "Ann", greet() { ... } }</code>. Vsak objekt se povezuje na <strong>prototip</strong>, in ko lastnost manjka, JavaScript pleza po tej verigi prototipov, da jo najde. Tako so skupne metode shranjene enkrat in jih uporablja mnogo objektov.' },
      { en: 'The <code>class</code> keyword gives a cleaner way to build objects with shared methods and <code>extends</code> for inheritance, but under the hood it still uses prototypes.', de: 'Das Schlüsselwort <code>class</code> bietet eine sauberere Art, Objekte mit geteilten Methoden und <code>extends</code> für Vererbung zu bauen, verwendet intern aber weiterhin Prototypen.', sl: 'Ključna beseda <code>class</code> ponuja čistejši način za gradnjo objektov s skupnimi metodami in <code>extends</code> za dedovanje, a pod pokrovom še vedno uporablja prototipe.' },
    ],
    how: [
      { en: '<strong>Objects and methods:</strong> access with dot or bracket notation; a method is just a function stored in a property.', de: '<strong>Objekte und Methoden:</strong> Zugriff per Punkt- oder Klammernotation; eine Methode ist nur eine in einer Eigenschaft gespeicherte Funktion.', sl: '<strong>Objekti in metode:</strong> dostop s piko ali oglatimi oklepaji; metoda je le funkcija, shranjena v lastnosti.' },
      { en: '<strong>Prototype chain:</strong> lookups climb from object to prototype to prototype until found or the chain ends at <code>null</code>.', de: '<strong>Prototypkette:</strong> Suchen steigen vom Objekt zum Prototyp zum Prototyp, bis gefunden oder die Kette bei <code>null</code> endet.', sl: '<strong>Veriga prototipov:</strong> iskanja se vzpenjajo od objekta do prototipa in naprej, dokler jih ne najdejo ali se veriga ne konča pri <code>null</code>.' },
      { en: '<strong>class / extends:</strong> declare fields and methods once; a subclass reuses and overrides them.', de: '<strong>class / extends:</strong> Felder und Methoden einmal deklarieren; eine Unterklasse nutzt und überschreibt sie.', sl: '<strong>class / extends:</strong> polja in metode deklariraj enkrat; podrazred jih ponovno uporabi in prepiše.' },
    ],
    pitfalls: [
      { en: 'Use <code>===</code> (strict equality), not <code>==</code>, which coerces types and gives surprises like <code>0 == ""</code> being true.', de: 'Nutze <code>===</code> (strenge Gleichheit), nicht <code>==</code>, das Typen umwandelt und Überraschungen wie <code>0 == ""</code> gleich wahr liefert.', sl: 'Uporabljaj <code>===</code> (strogo enakost), ne <code>==</code>, ki pretvarja tipe in prinaša presenečenja, kot da je <code>0 == ""</code> resnično.' },
      { en: 'The value of <code>this</code> depends on how a function is called, not where it is defined. Arrow functions capture the surrounding <code>this</code>.', de: 'Der Wert von <code>this</code> hängt davon ab, wie eine Funktion aufgerufen wird, nicht wo sie definiert ist. Pfeilfunktionen übernehmen das umgebende <code>this</code>.', sl: 'Vrednost <code>this</code> je odvisna od tega, kako je funkcija klicana, ne kje je definirana. Puščične funkcije prevzamejo okoliški <code>this</code>.' },
    ],
  },

  'async-js': {
    tldr: {
      en: 'JavaScript runs on a <strong>single thread</strong>, so slow work (network, timers) must not block it. The <strong>event loop</strong> runs queued callbacks when the stack is free. The tools evolved from <strong>callbacks</strong> to <strong>Promises</strong> to <strong>async/await</strong>.', de: 'JavaScript läuft in einem <strong>einzigen Thread</strong>, langsame Arbeit (Netz, Timer) darf ihn also nicht blockieren. Die <strong>Ereignisschleife</strong> führt eingereihte Rückrufe aus, sobald der Stapel frei ist. Die Werkzeuge entwickelten sich von <strong>Callbacks</strong> über <strong>Promises</strong> zu <strong>async/await</strong>.', sl: 'JavaScript teče v <strong>eni niti</strong>, zato ga počasno delo (omrežje, časovniki) ne sme blokirati. <strong>Zanka dogodkov</strong> izvaja uvrščene povratne klice, ko je sklad prost. Orodja so se razvila od <strong>povratnih klicev</strong> prek <strong>obljub</strong> do <strong>async/await</strong>.',
    },
    intro: [
      { en: 'A <strong>callback</strong> is a function you hand to an async operation to run when it finishes. Nesting many of them produces unreadable "callback hell".', de: 'Ein <strong>Callback</strong> ist eine Funktion, die du einer asynchronen Operation gibst, damit sie nach dem Ende läuft. Viele davon zu verschachteln erzeugt die unlesbare Callback-Hölle.', sl: '<strong>Povratni klic</strong> je funkcija, ki jo izročiš asinhroni operaciji, da se zažene, ko ta konča. Gnezdenje mnogih vodi v neberljivi "pekel povratnih klicev".' },
      { en: 'A <strong>Promise</strong> is an object representing a future value, in one of three states: <strong>pending</strong>, <strong>fulfilled</strong>, or <strong>rejected</strong>. You chain with <code>.then()</code>/<code>.catch()</code>, or write it linearly with <code>async</code>/<code>await</code>.', de: 'Ein <strong>Promise</strong> ist ein Objekt für einen zukünftigen Wert in einem von drei Zuständen: <strong>ausstehend</strong>, <strong>erfüllt</strong> oder <strong>abgelehnt</strong>. Du verkettest mit <code>.then()</code>/<code>.catch()</code> oder schreibst es linear mit <code>async</code>/<code>await</code>.', sl: '<strong>Obljuba</strong> je objekt, ki predstavlja prihodnjo vrednost, v enem od treh stanj: <strong>v teku</strong>, <strong>izpolnjena</strong> ali <strong>zavrnjena</strong>. Verižiš z <code>.then()</code>/<code>.catch()</code> ali napišeš linearno z <code>async</code>/<code>await</code>.' },
    ],
    how: [
      { en: '<strong>async</strong> marks a function that returns a Promise; <strong>await</strong> pauses inside it until a Promise settles, without blocking the whole page.', de: '<strong>async</strong> markiert eine Funktion, die ein Promise zurückgibt; <strong>await</strong> pausiert darin, bis ein Promise sich klärt, ohne die ganze Seite zu blockieren.', sl: '<strong>async</strong> označi funkcijo, ki vrne obljubo; <strong>await</strong> znotraj nje počaka, dokler se obljuba ne razreši, brez blokiranja cele strani.' },
      { en: 'Wrap <code>await</code> in <code>try/catch</code> to handle a rejected Promise as an ordinary error.', de: 'Umschliesse <code>await</code> mit <code>try/catch</code>, um ein abgelehntes Promise wie einen normalen Fehler zu behandeln.', sl: 'Ovij <code>await</code> v <code>try/catch</code>, da zavrnjeno obljubo obravnavaš kot navadno napako.' },
    ],
    pitfalls: [
      { en: 'Forgetting to <code>await</code> (or return) a Promise means the code moves on before the work is done, a very common bug.', de: 'Ein vergessenes <code>await</code> (oder return) bedeutet, dass der Code weiterläuft, bevor die Arbeit fertig ist, ein sehr häufiger Fehler.', sl: 'Pozabljen <code>await</code> (ali return) obljube pomeni, da se koda premakne naprej, preden je delo končano, zelo pogosta napaka.' },
    ],
  },

  'web-security': {
    tldr: {
      en: 'The web attacks every developer must defend against: <strong>XSS</strong> (inject a script into a page), <strong>SQL injection</strong> (inject SQL into a query), and <strong>CSRF</strong> (trick a logged-in user into a forged request). The golden rule: <strong>never trust client input</strong>.', de: 'Die Web-Angriffe, gegen die jeder Entwickler schützen muss: <strong>XSS</strong> (Skript in eine Seite einschleusen), <strong>SQL-Injection</strong> (SQL in eine Abfrage einschleusen) und <strong>CSRF</strong> (einen angemeldeten Nutzer zu einer gefälschten Anfrage verleiten). Die goldene Regel: <strong>traue nie der Client-Eingabe</strong>.', sl: 'Spletni napadi, pred katerimi se mora braniti vsak razvijalec: <strong>XSS</strong> (vrivanje skripta v stran), <strong>vrivanje SQL</strong> (vrivanje SQL v poizvedbo) in <strong>CSRF</strong> (zvijača, ki prijavljenega uporabnika napelje na ponarejeno zahtevo). Zlato pravilo: <strong>nikoli ne zaupaj vhodu odjemalca</strong>.',
    },
    intro: [
      { en: '<strong>XSS (Cross-Site Scripting):</strong> if user text is put into the page without escaping, an attacker can inject <code>&lt;script&gt;</code> that runs in other visitors&#39; browsers and steals their session.', de: '<strong>XSS (Cross-Site-Scripting):</strong> wird Nutzertext ungeschützt in die Seite gesetzt, kann ein Angreifer <code>&lt;script&gt;</code> einschleusen, das in den Browsern anderer läuft und ihre Sitzung stiehlt.', sl: '<strong>XSS (Cross-Site Scripting):</strong> če se uporabnikovo besedilo postavi v stran brez ubežanja, lahko napadalec vrine <code>&lt;script&gt;</code>, ki teče v brskalnikih drugih obiskovalcev in krade njihovo sejo.' },
      { en: '<strong>SQL injection:</strong> building a query by string-concatenating user input lets an attacker change its meaning (the classic <code>&#39; OR 1=1 --</code>).', de: '<strong>SQL-Injection:</strong> eine Abfrage per String-Verkettung aus Nutzereingabe zu bauen lässt einen Angreifer ihre Bedeutung ändern (der Klassiker <code>&#39; OR 1=1 --</code>).', sl: '<strong>Vrivanje SQL:</strong> gradnja poizvedbe s stikanjem nizov iz uporabnikovega vhoda napadalcu omogoči, da spremeni njen pomen (klasični <code>&#39; OR 1=1 --</code>).' },
    ],
    how: [
      { en: '<strong>Stop XSS:</strong> escape all user content on output, and set a Content-Security-Policy.', de: '<strong>XSS stoppen:</strong> alle Nutzerinhalte bei der Ausgabe escapen und eine Content-Security-Policy setzen.', sl: '<strong>Ustavi XSS:</strong> ubeži vsi uporabnikovi vsebini ob izpisu in nastavi Content-Security-Policy.' },
      { en: '<strong>Stop SQL injection:</strong> use <strong>parameterised queries</strong> (prepared statements), never string concatenation.', de: '<strong>SQL-Injection stoppen:</strong> <strong>parametrisierte Abfragen</strong> (Prepared Statements) nutzen, nie String-Verkettung.', sl: '<strong>Ustavi vrivanje SQL:</strong> uporabljaj <strong>parametrizirane poizvedbe</strong> (pripravljene stavke), nikoli stikanja nizov.' },
      { en: '<strong>Stop CSRF:</strong> require a per-form <strong>CSRF token</strong> and use <code>SameSite</code> cookies so other sites cannot ride your session.', de: '<strong>CSRF stoppen:</strong> ein <strong>CSRF-Token</strong> pro Formular verlangen und <code>SameSite</code>-Cookies nutzen, damit fremde Seiten deine Sitzung nicht mitreiten.', sl: '<strong>Ustavi CSRF:</strong> zahtevaj <strong>žeton CSRF</strong> na obrazec in uporabljaj piškotke <code>SameSite</code>, da druge strani ne morejo izkoristiti tvoje seje.' },
    ],
    pitfalls: [
      { en: 'Validating input only in the browser is no protection: the server must re-check everything, because an attacker bypasses the page entirely.', de: 'Eingaben nur im Browser zu prüfen schützt nicht: der Server muss alles erneut prüfen, denn ein Angreifer umgeht die Seite ganz.', sl: 'Preverjanje vhoda le v brskalniku ni zaščita: strežnik mora vse znova preveriti, saj napadalec stran povsem obide.' },
    ],
  },

  'web-frameworks': {
    tldr: {
      en: 'A <strong>web framework</strong> gives a project structure and reusable building blocks so you build faster and more securely than from scratch. <strong>Server-side</strong> frameworks (Laravel, Django) render pages and expose APIs; <strong>client-side</strong> ones (React, Vue) build interactive single-page apps in the browser.', de: 'Ein <strong>Web-Framework</strong> gibt einem Projekt Struktur und wiederverwendbare Bausteine, sodass du schneller und sicherer baust als von Grund auf. <strong>Serverseitige</strong> Frameworks (Laravel, Django) rendern Seiten und stellen APIs bereit; <strong>clientseitige</strong> (React, Vü) bauen interaktive Single-Page-Apps im Browser.', sl: '<strong>Spletno ogrodje</strong> daje projektu strukturo in gradnike za ponovno uporabo, da gradiš hitreje in varneje kot iz nič. <strong>Strežniška</strong> ogrodja (Laravel, Django) izrisujejo strani in ponujajo API-je; <strong>odjemalska</strong> (React, Vue) gradijo interaktivne enostranske aplikacije v brskalniku.',
    },
    intro: [
      { en: 'Server-side frameworks usually follow <strong>MVC</strong>: the <strong>model</strong> holds data, the <strong>view</strong> renders it, the <strong>controller</strong> handles requests. They bundle routing, database access, templating, sessions and security defaults.', de: 'Serverseitige Frameworks folgen meist <strong>MVC</strong>: das <strong>Modell</strong> hält Daten, die <strong>Ansicht</strong> stellt sie dar, der <strong>Controller</strong> bearbeitet Anfragen. Sie bündeln Routing, Datenbankzugriff, Templates, Sitzungen und Sicherheitsvorgaben.', sl: 'Strežniška ogrodja običajno sledijo <strong>MVC</strong>: <strong>model</strong> hrani podatke, <strong>pogled</strong> jih izriše, <strong>krmilnik</strong> obravnava zahteve. Združujejo usmerjanje, dostop do baze, predloge, seje in privzete varnostne nastavitve.' },
      { en: 'Client-side frameworks keep a component tree and re-render only what changed, giving app-like interactivity. Many apps combine both: an API on the server, a single-page app on the client.', de: 'Clientseitige Frameworks halten einen Komponentenbaum und rendern nur das Geänderte neu, was app-artige Interaktivität gibt. Viele Apps verbinden beides: eine API auf dem Server, eine Single-Page-App auf dem Client.', sl: 'Odjemalska ogrodja ohranjajo drevo komponent in znova izrišejo le tisto, kar se je spremenilo, kar daje aplikacijsko interaktivnost. Mnogo aplikacij združuje oboje: API na strežniku, enostranska aplikacija na odjemalcu.' },
    ],
    how: [
      { en: '<strong>Routing</strong> maps a URL to code; <strong>templating</strong> or components produce the HTML; an <strong>ORM</strong> maps objects to database rows.', de: '<strong>Routing</strong> bildet eine URL auf Code ab; <strong>Templates</strong> oder Komponenten erzeugen das HTML; ein <strong>ORM</strong> bildet Objekte auf Datenbankzeilen ab.', sl: '<strong>Usmerjanje</strong> preslika URL v kodo; <strong>predloge</strong> ali komponente ustvarijo HTML; <strong>ORM</strong> preslika objekte v vrstice baze.' },
    ],
    pitfalls: [
      { en: 'A framework saves time but adds a learning curve and lock-in; for a tiny static page, plain HTML/CSS/JS is often the better choice.', de: 'Ein Framework spart Zeit, bringt aber Lernkurve und Bindung; für eine winzige statische Seite ist schlichtes HTML/CSS/JS oft die bessere Wahl.', sl: 'Ogrodje prihrani čas, a prinese učno krivuljo in vezanost; za drobno statično stran je preprost HTML/CSS/JS pogosto boljša izbira.' },
    ],
  },
}
